### ISSUE TITLE
file json

### ISSUE THREAD

**Issue by irulvam** [veo-labs/ldap-server-mock#1]
hi, this is awesome. but i don't understand how to setting of 2 json file. can you explain more example for me?

thanks

**Comment by maxime-beguin** [comment]
Hi @irulvam.

This project aims to replace an LDAP server for authentication purpose when executing tests. Actually it can't be used for more complex search requests.

Here is a complete functional example to configure the LDAP server mock and interrogate it to authenticate a user.

First create a file containing the LDAP server mock configuration:

**server-conf.json**:
```json
{
  "port": 3004,
  "userLoginAttribute": "cn",
  "searchBase": "dc=test",
  "searchFilter": "(&(objectclass=person)(cn={{username}}))"
}
```

With:

- **port**: The port the server will listen to
- **userLoginAttribute**: The LDAP attribute holding the login of the user you want to authenticate. It must correspond to a user property in the users.json file below
- **searchBase**: The LDAP base you will interrogate with your LDAP client
- **searchFilter**: The search filter you will use to authenticate your user with your LDAP client with **{{username}}** the placeholder in the filter which will contain the user login

Then create a file containing the users you want to have inside your LDAP server:

**users.json**:
```json
[
  {
    "dn": "cn=user1,dc=test",
    "cn": "user1-login",
    "attribute1": "value1",
    "attribute2": "value2"
  },
  {
    "dn": "cn=user2,dc=test",
    "cn": "user2-login",
    "attribute1": "value3",
    "attribute2": "value4"
  }
]
```
With for each user:

- **dn**: A valid LDAP distinguished name for the user
- **cn**: The user login as we specified in server-conf.json that the **cn** property holds the user login
- **attribute1** | **attribute2** | **and more** : Any number of properties that will be returned as is when authenticating the user

You can now launch your LDAP server using:

`node node_modules/ldap-server-mock/server.js --conf="/path/to/the/server-conf.json" --database="path/to/the/users.json"`

Now that your server is running on port 3004 and listens to the search base "dc=test" you can authenticate your user with your client. The following example, with the ldapsearch command, authenticates the user with login **user1-login**:

`ldapsearch -x -H ldap://127.0.0.1:3004 -b dc=test '(&(objectclass=person)(cn=user1-login))'`

> dn: cn=user1, dc=test
> cn: user1-login
> attribute1: value1
> attribute2: value
