### ISSUE TITLE
Please add basic authentication support to LDAP mock server

### ISSUE THREAD

**Issue by JonCook** [veo-labs/ldap-server-mock#23]
Hi,

Nice little project!! I've set up my LDAP mock server without issue and it works with no problems using ldapsearch, however, I've realised now that when I use my Java client to test against my mock ldap. It is always trying to authenticate and consequently fails. 

I can't change my app not to authenticate and I suspect no one is really using LDAP without authentication, so I was wondering if you could add a simple enhancement to support this. Looking at ldapjs, it wouldn't be too hard I think?:

Maybe in the start method something like this:

```
this.app.bind('cn=root', (req, res, next) => {
  if (req.dn.toString() !== 'cn=root' || req.credentials !== 'secret')
    return next(new ldap.InvalidCredentialsError());

  res.end();
  return next();
});
```

It seems a shame to have to fork and duplicate all the code, just to add this functionality.

Many Thanks,
Jonathan

**Comment by maxime-beguin** [comment]
Hi @JonCook,

Thank you for your constructive criticism!

I don't think I really understand what you are trying to do.
There is actually no restriction on binding. The only restriction is that the user you bind with must have a **D**istinguished **N**ame under `searchBase` ( defined in `ldap-server-mock-conf.json`).
As an exemple, If your `searchBase` is set to `dc=test` you can bind with `dc=test` or `cn=root,dc=test` or whatever **D**istinguished **N**ame as far as it ends by `dc=test`.

You can try the following LDAP command to see it in action:

`ldapsearch -D "cn=root,dc=test" -H ldap://127.0.0.1:3004 -b "dc=test" "(&(objectclass=person)(cn=user-login))" attribute1 attribute2`

Note that user with **D**istinguished **N**ame `cn=root,dc=test` should not necessary be present in the list of users but you can add it for clarity.

Hope it helps.

**Comment by JonCook** [comment]
Hi @maxime-beguin,

Thanks for your reply! This helped a lot. I realized I just had to set my username to be the same as the search base from my Java client and my Java client continues to work with simple authentication against the mock LDAP server. Cool :-)

I'll close this ticket. Thanks again
Jon

**Comment by maxime-beguin** [comment]
Hi @JonCook,

You're welcome.
Thank you for taking time to explain what was the solution for you!
