### ISSUE TITLE
Start programatically

### ISSUE THREAD

**Issue by cope** [veo-labs/ldap-server-mock#24]
Hi, is there a way to start the mock server from the code, to use in testing suites?

**Comment by maxime-beguin** [comment]
Hi @cope,

Yes you can use NodeJs [Child process](https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html) to start the LDAP server mock from your tests.
The LDAP server mock will emit `{status: 'started'}` on parent process when it is ready.

Hope it helps.

**Comment by cope** [comment]
Awesome, will try it now!

**Comment by cope** [comment]
Hi @maxime-beguin, can we also set groups in database, in addition to users?

**Comment by cope** [comment]
I keep getting ENOENT with spawn 😞 

Both `npx ldap-server-mock --conf=...` and `ldap-server-mock --conf=...` work from command line, but throw ENOENT with spawn 😞

**Comment by cope** [comment]
Hmmm, even `npx -h` throws ENOENT with spawn 😞

**Comment by cope** [comment]
The best I can get is mocha timeout and left over node processes I then have to kill 😞 

Is there a working example with spawn, to look at?

**Comment by maxime-beguin** [comment]
Hi @cope!

Have you tried [forking](https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html#child_processforkmodulepath-args-options) using directly `node` instead of `npx`?

**Comment by cope** [comment]
No, but to be fair, exporting a module like LdapMockServer to be used in testing suites with start() and stop() would be way better...

**Comment by maxime-beguin** [comment]
I agree. It would probably be more easy to use in some cases.
Maybe in a future version.

**Comment by royetadmor** [comment]
@cope I had the same issue (starting and closing the server for testing purposes) and I can suggest this workaround:
Start the server: `npx ldap-server-mock --conf=./ldap_server_config.json --database=./ldap_user_data.json &` (the `&` is for running the server in the background)
Close the server: `pgrep -f ldap-server-mock | xargs kill -9`
Hope this helps! 😄

**Comment by dominic-p** [comment]
I'm interested in using this for testing as well. I think it would really benefit from a Node.js API instead of having to deal with child_process.

I could submit a PR if that would be helpful. I'm thinking just add a `main` entry to package.json pointing to a new file that exports a "createSearver" function that you can call and pass in your config and db objects.

Thanks for the fantastic software, by the way.

**Comment by maxime-beguin** [comment]
HI @dominic-p,

Thank you for your support, sadly I currently don't have much time to work on this project.
I should be able to work on this during november.

You can of course submit a pull request but I won't be able to address it until november.
As you probably aslo have things to do on your side, I suggest you to wait until november.

Thanks again.

**Comment by dominic-p** [comment]
Thanks for the feedback, and I totally understand. If I have some time to work on a PR I will, otherwise I'll wait on this for the time being.

**Comment by maxime-beguin** [comment]
Hi @dominic-p, hi @cope, hi @royetadmor,

This feature has been implemented on the `develop` branch and will be available in version `6.0.0` soon.

Thank you for your support.

**Comment by dominic-p** [comment]
So cool! Thanks for that. :)
