### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by bluscreen** [veo-labs/ldap-server-mock#5]
would be nice to know that you need:

- python installed (2.x as 3 isnt supported by npm)

> If you haven't got python installed along with all the node-gyp dependencies, simply open Powershell > or Git Bash with administrator privileges and execute:
> 
> npm install --global --production windows-build-tools
> and then to install the package:
> 
> npm install --global node-gyp
> once installed, you will have all the node-gyp dependencies downloaded, but you still need the environment variable. Validate Python is indeed found in the correct folder:
> C:\Users\ben\.windows-build-tools\python27\python.exe 
> Note - it uses python 2.7 not 3.x as it is not supported

- windows needs some .net 2.0 framework installation which i cannot install as i have some never version present

could resolve this issue just installing with -g flag ?!

cheers

**Comment by maxime-beguin** [comment]
You're rigth, most of NodeJS modules has, at least, one dependency which makes use of native addons and thus need to be compiled using **[node-gyp](https://www.npmjs.com/package/node-gyp)**.
I'm not an experienced Windows user but i think several versions of the .net framework can cohabit.
