### ISSUE TITLE
Add example command using common ldap client

### ISSUE THREAD

**Issue by cvgw** [veo-labs/ldap-server-mock#8]
I think it would be very useful to new users to have an example search using a common tool like `ldapsearch`.

Something like 
```
$ ldapsearch -x -h localhost -p 3004 -b "dc=test" "(&(objectclass=person)(cn=user-login))"
```

I think adding this to the README would help clear up confusion for new users.

**Comment by maxime-beguin** [comment]
@cvgw: thank you for the advice, an example has been added to the README.md file in branch develop. It will be released soon.

**Comment by maxime-beguin** [comment]
Released.
